name: BlockShuffle
version: 1.2.2
main: tech.reisu1337.blockshuffle.BlockShuffle
api-version: 1.18
authors: [ Reisu1337 ]
description: A simple Block Shuffle game for Minecraft 1.18
website: reisu1337.tech

commands:
  blockshuffle:
    description: ""

permissions:
  blockshuffle.admin:
    default: op
