start: The Block Shuffle game has begun!
starterror: The game is already in progress!
materials:
  - ACACIA_DOOR
  - ACACIA_FENCE
  - ACACIA_FENCE_GATE
  - ACACIA_LEAVES
  - ACACIA_LOGS
  - ACACIA_PLANKS
  - ACACIA_PRESSURE_PLATE
  - ACACIA_SLAB
  - ACACIA_STAIRS
  - ACACIA_TRAPDOOR
  - ACACIA_WOOD
  - ACTIVATOR_RAIL
  - AMETHYST_BLOCK
  - ANDESITE
  - ANDESITE_SLAB
  - ANDESITE_STAIRS
  - ANDESITE_WALL
  - ANVIL
  - BARREL
  - BEDROCK
  - BEEHIVE
  - BELL
  - BIRCH_DOOR
  - BIRCH_FENCE
  - BIRCH_FENCE_GATE
  - BIRCH_LEAVES
  - BIRCH_LOG
  - BIRCH_PLANKS
  - BIRCH_PRESSURE_PLATE
  - BIRCH_SLAB
  - BIRCH_STAIRS
  - BIRCH_TRAPDOOR
  - BLACK_BED
  - BLACK_CARPET
  - BLACK_CONCRETE
  - BLACK_CONCRETE_POWDER
  - BLACK_GLAZED_TERRACOTTA
  - BLACK_STAINED_GLASS
  - BLACK_STAINED_GLASS_PANE
  - BLACK_TERRACOTTA
  - BLACK_WOOL
  - BLAST_FURNACE
  - BLUE_BED
  - BLUE_CARPET
  - BLUE_CONCRETE
  - BLUE_CONCRETE_POWDER
  - BLUE_GLAZED_TERRACOTTA
  - BLUE_STAINED_GLASS
  - BLUE_STAINED_GLASS_PANE
  - BLUE_TERRACOTTA
  - BOOKSHELF
  - BRICK_STAIRS
  - BRICK_WALL
  - BRICKS
  - BROWN_BED
  - BROWN_CARPET
  - BROWN_CONCRETE
  - BROWN_CONCRETE_POWDER
  - BROWN_GLAZED_TERRACOTTA
  - BROWN_MUSHROOM_BLOCK
  - BROWN_STAINED_GLASS
  - BROWN_STAINED_GLASS_PANE
  - BROWN_TERRACOTTA
  - BROWN_WOOL
  - CACTUS
  - CAMPFIRE
  - CAKE
  - CARTOGRAPHY_TABLE
  - CAULDRON
  - CHEST
  - COAL_BLOCK
  - COAL_ORE
  - COARSE_DIRT
  - COBBLED_DEEPSLATE
  - COBBLED_DEEPSLATE_SLAB
  - COBBLED_DEEPSLATE_STAIRS
  - COBBLED_DEEPSLATE_WALL
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - COBBLESTONE_WALL
  - COBWEB
  - COMPOSTER
  - COPPER_BLOCK
  - COPPER_ORE
  - CYAN_BED
  - CYAN_CARPET
  - CYAN_CONCRETE
  - CYAN_CONCRETE_POWDER
  - CYAN_GLAZED_TERRACOTTA
  - CYAN_STAINED_GLASS
  - CYAN_STAINED_GLASS_PANE
  - CYAN_TERRACOTTA
  - CYAN_WOOL