start: The Block Shuffle game is beginning!
starterror: The game is already in progress!
stopgame: The Block Shuffle game has been ended!
stoperror: No Block Shuffle game running!
materials:
  - ACACIA_DOOR
  - ACACIA_FENCE
  - ACACIA_FENCE_GATE
  - ACACIA_LEAVES
  - ACACIA_LOGS
  - ACACIA_PLANKS
  - ACACIA_PRESSURE_PLATE
  - ACACIA_SLAB
  - ACACIA_STAIRS
  - ACACIA_TRAPDOOR
  - ACACIA_WOOD
  - AMETHYST_BLOCK
  - ANDESITE
  - ANDESITE_SLAB
  - ANDESITE_STAIRS
  - ANDESITE_WALL
  - ANVIL
  - BARREL
  - BEDROCK
  - BEEHIVE
  - BELL
  - BIRCH_DOOR
  - BIRCH_FENCE
  - BIRCH_FENCE_GATE
  - BIRCH_LEAVES
  - BIRCH_LOG
  - BIRCH_PLANKS
  - BIRCH_PRESSURE_PLATE
  - BIRCH_SLAB
  - BIRCH_STAIRS
  - BIRCH_TRAPDOOR
  - BLACK_BED
  - BLACK_CARPET
  - BLACK_CONCRETE
  - BLACK_CONCRETE_POWDER
  - BLACK_GLAZED_TERRACOTTA
  - BLACK_STAINED_GLASS
  - BLACK_STAINED_GLASS_PANE
  - BLACK_TERRACOTTA
  - BLACK_WOOL
  - BLAST_FURNACE
  - BLUE_BED
  - BLUE_CARPET
  - BLUE_CONCRETE
  - BLUE_CONCRETE_POWDER
  - BLUE_GLAZED_TERRACOTTA
  - BLUE_STAINED_GLASS
  - BLUE_STAINED_GLASS_PANE
  - BLUE_TERRACOTTA
  - BOOKSHELF
  - BRICK_STAIRS
  - BRICK_WALL
  - BRICKS
  - BROWN_BED
  - BROWN_CARPET
  - BROWN_CONCRETE
  - BROWN_CONCRETE_POWDER
  - BROWN_GLAZED_TERRACOTTA
  - BROWN_MUSHROOM_BLOCK
  - BROWN_STAINED_GLASS
  - BROWN_STAINED_GLASS_PANE
  - BROWN_TERRACOTTA
  - BROWN_WOOL
  - CACTUS
  - CAMPFIRE
  - CAKE
  - CARTOGRAPHY_TABLE
  - CAULDRON
  - CHEST
  - COAL_BLOCK
  - COAL_ORE
  - COARSE_DIRT
  - COBBLED_DEEPSLATE
  - COBBLED_DEEPSLATE_SLAB
  - COBBLED_DEEPSLATE_STAIRS
  - COBBLED_DEEPSLATE_WALL
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - COBBLESTONE_WALL
  - COBWEB
  - COMPOSTER
  - COPPER_BLOCK
  - COPPER_ORE
  - CYAN_BED
  - CYAN_CARPET
  - CYAN_CONCRETE
  - CYAN_CONCRETE_POWDER
  - CYAN_GLAZED_TERRACOTTA
  - CYAN_STAINED_GLASS
  - CYAN_STAINED_GLASS_PANE
  - CYAN_TERRACOTTA
  - CYAN_WOOL
  - DARK_OAK_DOOR
  - DARK_OAK_FENCE
  - DARK_OAK_FENCE_GATE
  - DARK_OAK_LEAVES
  - DARK_OAK_LOG
  - DARK_OAK_PLANKS
  - DARK_OAK_PRESSURE_PLATE
  - DARK_OAK_SLAB
  - DARK_OAK_STAIRS
  - DARK_OAK_TRAPDOOR
  - DARK_OAK_WOOD
  - DEEPSLATE
  - DEEPSLATE_BRICK_SLAB
  - DEEPSLATE_BRICK_STAIRS
  - DEEPSLATE_BRICK_WALL
  - DEEPSLATE_BRICKS
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_TILE_SLAB
  - DEEPSLATE_TILE_STAIRS
  - DEEPSLATE_TILE_WALL
  - DEEPSLATE_TILES
  - DIAMOND_ORE
  - DIORITE_SLAB
  - DIORITE_STAIRS
  - DIORITE_WALL
  - DIRT
  - DIRT_PATH
  - DISPENSER
  - DROPPER
  - EMERALD_ORE
  - ENCHANTING_TABLE
  - FLETCHING_TABLE
  - FLOWER_POT
  - FURNACE
  - GLASS
  - GLASS_PANE
  - GOLD_ORE
  - GRANITE
  - GRANITE_SLAB
  - GRANITE_STAIRS
  - GRANITE_WALL
  - GRASS_BLOCK
  - GRAVEL
  - GRAY_BED
  - GRAY_CARPET
  - GRAY_CONCRETE
  - GRAY_CONCRETE_POWDER
  - GRAY_GLAZED_TERRACOTTA
  - GRAY_STAINED_GLASS
  - GRAY_STAINED_GLASS_PANE
  - GRAY_TERRACOTTA
  - GRAY_WOOL
  - GREEN_BED
  - GREEN_CARPET
  - GREEN_CONCRETE
  - GREEN_CONCRETE_POWDER
  - GREEN_GLAZED_TERRACOTTA
  - GREEN_STAINED_GLASS
  - GREEN_STAINED_GLASS_PANE
  - GREEN_TERRACOTTA
  - GREEN_WOOL
  - GRINDSTONE
  - HAY_BLOCK
  - HOPPER
  - ICE
  - IRON_BARS
  - IRON_DOOR
  - IRON_ORE
  - IRON_TRAPDOOR
  - JUKEBOX
  - JUNGLE_DOOR
  - JUNGLE_FENCE
  - JUNGLE_FENCE_GATE
  - JUNGLE_LEAVES
  - JUNGLE_LOG
  - JUNGLE_PLANKS
  - JUNGLE_PRESSURE_PLATE
  - JUNGLE_SLAB
  - JUNGLE_STAIRS
  - JUNGLE_TRAPDOOR
  - JUNGLE_WOOD
  - LANTERN
  - LAPIS_ORE
  - LECTERN
  - LIGHT_BLUE_BED
  - LIGHT_BLUE_CARPET
  - LIGHT_BLUE_CONCRETE
  - LIGHT_BLUE_CONCRETE_POWDER
  - LIGHT_BLUE_GLAZED_TERRACOTTA
  - LIGHT_BLUE_STAINED_GLASS
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - LIGHT_BLUE_TERRACOTTA
  - LIGHT_BLUE_WOOL
  - LIGHT_GRAY_BED
  - LIGHT_GRAY_CARPET
  - LIGHT_GRAY_CONCRETE
  - LIGHT_GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_GLAZED_TERRACOTTA
  - LIGHT_GRAY_STAINED_GLASS
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - LIGHT_GRAY_TERRACOTTA
  - LIGHT_GRAY_WOOL
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - LILY_PAD
  - LIME_BED
  - LIME_CARPET
  - LIME_CONCRETE
  - LIME_CONCRETE_POWDER
  - LIME_GLAZED_TERRACOTTA
  - LIME_STAINED_GLASS
  - LIME_STAINED_GLASS_PANE
  - LIME_TERRACOTTA
  - LIME_WOOL
  - LOOM
  - MAGENTA_BED
  - MAGENTA_CARPET
  - MAGENTA_CONCRETE
  - MAGENTA_CONCRETE_POWDER
  - MAGENTA_GLAZED_TERRACOTTA
  - MAGENTA_STAINED_GLASS
  - MAGENTA_STAINED_GLASS_PANE
  - MAGENTA_TERRACOTTA
  - MAGENTA_WOOL
  - MOSSY_COBBLESTONE
  - OAK_DOOR
  - OAK_FENCE
  - OAK_FENCE_GATE
  - OAK_LEAVES
  - OAK_LOG
  - OAK_PLANKS
  - OAK_PRESSURE_PLATE
  - OAK_SLAB
  - OAK_STAIRS
  - OAK_TRAPDOOR
  - OAK_WOOD
  - OBSERVER
  - OBSIDIAN
  - ORANGE_BED
  - ORANGE_CARPET
  - ORANGE_CONCRETE
  - ORANGE_CONCRETE_POWDER
  - ORANGE_GLAZED_TERRACOTTA
  - ORANGE_STAINED_GLASS
  - ORANGE_STAINED_GLASS_PANE
  - ORANGE_TERRACOTTA
  - ORANGE_WOOL
  - PINK_BED
  - PINK_CARPET
  - PINK_CONCRETE
  - PINK_CONCRETE_POWDER
  - PINK_GLAZED_TERRACOTTA
  - PINK_STAINED_GLASS
  - PINK_STAINED_GLASS_PANE
  - PINK_TERRACOTTA
  - PINK_WOOL
  - PODZOL
  - PURPLE_BED
  - PURPLE_CARPET
  - PURPLE_CONCRETE
  - PURPLE_CONCRETE_POWDER
  - PURPLE_GLAZED_TERRACOTTA
  - PURPLE_STAINED_GLASS
  - PURPLE_STAINED_GLASS_PANE
  - PURPLE_TERRACOTTA
  - PURPLE_WOOL
  - RED_BED
  - RED_CARPET
  - RED_CONCRETE
  - RED_CONCRETE_POWDER
  - RED_GLAZED_TERRACOTTA
  - RED_STAINED_GLASS
  - RED_STAINED_GLASS_PANE
  - RED_TERRACOTTA
  - RED_WOOL
  - REDSTONE_ORE
  - SAND
  - SANDSTONE
  - SANDSTONE_SLAB
  - SANDSTONE_STAIRS
  - SANDSTONE_WALL
  - SMITHING_TABLE
  - SPRUCE_DOOR
  - SPRUCE_FENCE
  - SPRUCE_FENCE_GATE
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_PLANKS
  - SPRUCE_PRESSURE_PLATE
  - SPRUCE_SLAB
  - SPRUCE_STAIRS
  - SPRUCE_TRAPDOOR
  - SPRUCE_WOOD
  - STONE
  - STONE_BRICK_SLAB
  - STONE_BRICK_STAIRS
  - STONE_BRICKS
  - STONE_SLAB
  - STONE_STAIRS
  - STRIPPED_ACACIA_LOG
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_BIRCH_LOG
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_DARK_OAK_WOOD
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_OAK_LOG
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_SPRUCE_WOOD
  - TERRACOTTA
  - TNT
  - TRAPPED_CHEST
  - TRIPWIRE
  - TUFF
  - WHITE_BED
  - WHITE_CARPET
  - WHITE_CONCRETE
  - WHITE_CONCRETE_POWDER
  - WHITE_GLAZED_TERRACOTTA
  - WHITE_STAINED_GLASS
  - WHITE_STAINED_GLASS_PANE
  - WHITE_TERRACOTTA
  - WHITE_WOOL
  - YELLOW_BED
  - YELLOW_CARPET
  - YELLOW_CONCRETE
  - YELLOW_CONCRETE_POWDER
  - YELLOW_GLAZED_TERRACOTTA
  - YELLOW_STAINED_GLASS
  - YELLOW_STAINED_GLASS_PANE
  - YELLOW_TERRACOTTA
  - YELLOW_WOOL
colour_materials:
  - BLACK_BED
  - BLACK_CARPET
  - BLACK_CONCRETE
  - BLACK_CONCRETE_POWDER
  - BLACK_GLAZED_TERRACOTTA
  - BLACK_STAINED_GLASS
  - BLACK_STAINED_GLASS_PANE
  - BLACK_TERRACOTTA
  - BLACK_WOOL
  - BLUE_BED
  - BLUE_CARPET
  - BLUE_CONCRETE
  - BLUE_CONCRETE_POWDER
  - BLUE_GLAZED_TERRACOTTA
  - BLUE_STAINED_GLASS
  - BLUE_STAINED_GLASS_PANE
  - BLUE_TERRACOTTA
  - BROWN_BED
  - BROWN_CARPET
  - BROWN_CONCRETE
  - BROWN_CONCRETE_POWDER
  - BROWN_GLAZED_TERRACOTTA
  - BROWN_MUSHROOM_BLOCK
  - BROWN_STAINED_GLASS
  - BROWN_STAINED_GLASS_PANE
  - BROWN_TERRACOTTA
  - BROWN_WOOL
  - CYAN_BED
  - CYAN_CARPET
  - CYAN_CONCRETE
  - CYAN_CONCRETE_POWDER
  - CYAN_GLAZED_TERRACOTTA
  - CYAN_STAINED_GLASS
  - CYAN_STAINED_GLASS_PANE
  - CYAN_TERRACOTTA
  - CYAN_WOOL
  - GRAY_BED
  - GRAY_CARPET
  - GRAY_CONCRETE
  - GRAY_CONCRETE_POWDER
  - GRAY_GLAZED_TERRACOTTA
  - GRAY_STAINED_GLASS
  - GRAY_STAINED_GLASS_PANE
  - GRAY_TERRACOTTA
  - GRAY_WOOL
  - GREEN_BED
  - GREEN_CARPET
  - GREEN_CONCRETE
  - GREEN_CONCRETE_POWDER
  - GREEN_GLAZED_TERRACOTTA
  - GREEN_STAINED_GLASS
  - GREEN_STAINED_GLASS_PANE
  - GREEN_TERRACOTTA
  - GREEN_WOOL
  - LIGHT_BLUE_BED
  - LIGHT_BLUE_CARPET
  - LIGHT_BLUE_CONCRETE
  - LIGHT_BLUE_CONCRETE_POWDER
  - LIGHT_BLUE_GLAZED_TERRACOTTA
  - LIGHT_BLUE_STAINED_GLASS
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - LIGHT_BLUE_TERRACOTTA
  - LIGHT_BLUE_WOOL
  - LIGHT_GRAY_BED
  - LIGHT_GRAY_CARPET
  - LIGHT_GRAY_CONCRETE
  - LIGHT_GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_GLAZED_TERRACOTTA
  - LIGHT_GRAY_STAINED_GLASS
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - LIGHT_GRAY_TERRACOTTA
  - LIGHT_GRAY_WOOL
  - LIME_BED
  - LIME_CARPET
  - LIME_CONCRETE
  - LIME_CONCRETE_POWDER
  - LIME_GLAZED_TERRACOTTA
  - LIME_STAINED_GLASS
  - LIME_STAINED_GLASS_PANE
  - LIME_TERRACOTTA
  - LIME_WOOL
  - MAGENTA_BED
  - MAGENTA_CARPET
  - MAGENTA_CONCRETE
  - MAGENTA_CONCRETE_POWDER
  - MAGENTA_GLAZED_TERRACOTTA
  - MAGENTA_STAINED_GLASS
  - MAGENTA_STAINED_GLASS_PANE
  - MAGENTA_TERRACOTTA
  - MAGENTA_WOOL
  - ORANGE_BED
  - ORANGE_CARPET
  - ORANGE_CONCRETE
  - ORANGE_CONCRETE_POWDER
  - ORANGE_GLAZED_TERRACOTTA
  - ORANGE_STAINED_GLASS
  - ORANGE_STAINED_GLASS_PANE
  - ORANGE_TERRACOTTA
  - ORANGE_WOOL
  - PINK_BED
  - PINK_CARPET
  - PINK_CONCRETE
  - PINK_CONCRETE_POWDER
  - PINK_GLAZED_TERRACOTTA
  - PINK_STAINED_GLASS
  - PINK_STAINED_GLASS_PANE
  - PINK_TERRACOTTA
  - PURPLE_BED
  - PURPLE_CARPET
  - PURPLE_CONCRETE
  - PURPLE_CONCRETE_POWDER
  - PURPLE_GLAZED_TERRACOTTA
  - PURPLE_STAINED_GLASS
  - PURPLE_STAINED_GLASS_PANE
  - PURPLE_TERRACOTTA
  - PURPLE_WOOL
  - RED_BED
  - RED_CARPET
  - RED_CONCRETE
  - RED_CONCRETE_POWDER
  - RED_GLAZED_TERRACOTTA
  - RED_STAINED_GLASS
  - RED_STAINED_GLASS_PANE
  - RED_TERRACOTTA
  - RED_WOOL
  - WHITE_BED
  - WHITE_CARPET
  - WHITE_CONCRETE
  - WHITE_CONCRETE_POWDER
  - WHITE_GLAZED_TERRACOTTA
  - WHITE_STAINED_GLASS
  - WHITE_STAINED_GLASS_PANE
  - WHITE_TERRACOTTA
  - WHITE_WOOL
  - YELLOW_BED
  - YELLOW_CARPET
  - YELLOW_CONCRETE
  - YELLOW_CONCRETE_POWDER
  - YELLOW_GLAZED_TERRACOTTA
  - YELLOW_STAINED_GLASS
  - YELLOW_STAINED_GLASS_PANE
  - YELLOW_TERRACOTTA
  - YELLOW_WOOL
easy_materials:
  - GRASS_BLOCK
  - STONE
  - COBBLESTONE
  - SAND
  - GRAVEL
  - COAL_ORE
  -